[global]
developmentMode = false

[server]
headless = true
port = 8501
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[runner]
magicEnabled = true 

[client]
showErrorDetails = false 